### ISSUE TITLE
Missing Django 1.7 migration with aldryn-newsblog==1.0.9

### ISSUE THREAD

**Issue by trawick** [divio/aldryn-newsblog#323]
Migration 0006 seems to be needed:

```
$ python manage.py makemigrations --dry-run
Migrations for 'aldryn_newsblog':
  0006_auto_20151113_2216.py:
    - Change Meta options on newsblogconfig
    - Change Meta options on newsblogconfigtranslation
    - Alter field lead_in on articletranslation
    - Alter field app_data on newsblogconfig
    - Alter field template_prefix on newsblogconfig
```

My environment:

Python 3.4.3, Django 1.7.10, 

```
aldryn-apphooks-config==0.2.6
aldryn-boilerplates==0.7.3
aldryn-categories==1.0.1
aldryn-common==1.0.0
aldryn-newsblog==1.0.9
aldryn-people==1.1.2
aldryn-reversion==1.0.1
aldryn-translation-tools==0.2.1
amqp==1.4.7
anyjson==0.3.3
astroid==1.0.1
backport-collections==0.1
beautifulsoup4==4.3.2
billiard==3.3.0.21
celery==3.1.17
cmsplugin-filer==0.10.2
coverage==3.7.1
Django==1.7.10
django-appconf==1.0.1
django-appdata==0.1.4
django-classy-tags==0.6.2
django-cms==3.1.3
django-cors-headers==1.0.0
django-debug-toolbar==1.2.1
django-filer==0.9.12
django-filter==0.9.1
django-mptt==0.6.1
django-parler==1.5.1
django-phonenumber-field==0.7.2
django-polymorphic==0.7.2
django-reversion==1.8.5
django-sekizai==0.8.2
django-sortedm2m==1.0.2
django-taggit==0.17.3
django-treebeard==3.0
djangocms-admin-style==0.2.2
djangocms-text-ckeditor==2.7.0
djangorestframework==3.1.1
easy-thumbnails==2.2
factory-boy==2.4.1
flake8==2.2.5
future==0.15.2
html5lib==0.999
jira==0.35
kombu==3.0.29
logilab-common==0.61.0
lxml==3.5.0
Markdown==2.5.2
mccabe==0.3
oauthlib==0.7.2
pep8==1.5.7
phonenumbers==7.1.1
Pillow==2.9.0
psycopg2==2.5.4
pyflakes==0.8.1
pylint==1.1.0
python-dateutil==2.4.2
python-slugify==1.1.4
pytz==2015.7
PyYAML==3.10
requests==2.5.1
requests-oauthlib==0.4.2
selenium==2.45.0
six==1.6.1
sorl-thumbnail==12.3
South==1.0.2
sqlparse==0.1.11
tlslite==0.4.8
transifex-client==0.11
Unidecode==0.4.18
urllib3==1.12
xlrd==0.9.3
xlwt-future==0.8.0
YURL==0.13
```

**Comment by trawick** [comment]
I guess this little bit -- ``- Alter field app_data on newsblogconfig`` is the same as https://github.com/aldryn/aldryn-faq/issues/146, and the rest of the field changes indicated by Python 3.4 + Django 1.7.10 are a similar issue.  I'll try to dig into this deeper soon.

**Comment by mkoistinen** [comment]
Hi @trawick, does PR #337 satisfy this for you?

**Comment by trawick** [comment]
Hello, thanks for your response/efforts!

With Python 3.4 and the now-current master branch with your pull request, I'm getting just these as missing:

```
$ python manage.py makemigrations --dry-run
Migrations for 'aldryn_newsblog':
  0007_auto_20160106_1704.py:
    - Alter field app_data on newsblogconfig
    - Alter field template_prefix on newsblogconfig
```

(installing ``git+git://github.com/aldryn/aldryn-newsblog.git@d3707fea3a27eb74f4fd371a05e7771e13adb07b#egg=aldryn-newsblog`` via pip)

With Python 2.7 I'm getting just this one:

```
$ python manage.py makemigrations --dry-run
Migrations for 'aldryn_newsblog':
  0007_auto_20160106_1838.py:
    - Alter field template_prefix on newsblogconfig
```

This is a slightly simplified setup from my original report.

Python versions: 2.7.6 and 3.4.3
requirements.txt used with both:

```
Babel==2.2.0
Django==1.7.10
Pillow==3.0.0
URLObject==2.4.0
Unidecode==0.04.18
YURL==0.13
aldryn-apphooks-config==0.2.6
aldryn-boilerplates==0.7.3
aldryn-categories==1.0.1
aldryn-common==1.0.0
aldryn-people==1.1.3
aldryn-reversion==1.0.3
aldryn-search==0.2.10
aldryn-translation-tools==0.2.1
backport-collections==0.1
django-admin-sortable==2.0.7
django-admin-sortable2==0.6.2
django-appconf==1.0.1
django-appdata==0.1.5
django-classy-tags==0.7.0
django-cms==3.2.0
django-filer==1.0.6
django-formtools==1.0
django-haystack==2.4.1
django-mptt==0.8.0
django-parler==1.5.1
django-phonenumber-field==1.0.0
django-polymorphic==0.8.1
django-reversion==1.8.7
django-sekizai==0.9.0
django-sortedm2m==1.1.1
django-spurl==0.6.2
django-standard-form==1.1.1
django-taggit==0.17.6
django-treebeard==3.0
djangocms-admin-style==1.0.7
djangocms-text-ckeditor==2.8.0
easy-thumbnails==2.3
html5lib==0.9999999
lxml==3.5.0
phonenumbers==7.2.2
python-dateutil==2.4.2
python-slugify==1.1.4
pytz==2015.7
six==1.10.0
git+git://github.com/aldryn/aldryn-newsblog.git@d3707fea3a27eb74f4fd371a05e7771e13adb07b#egg=aldryn-newsblog
```

**Comment by czpython** [comment]
@trawick Django migrations are extremely sensitive.

Example:

```python
field = models.CharField(choices=settings.LANGUAGES)
```

If I create a migration for the field above and then add or remove a language from
``settings.LANGUAGES``, Django will report that there's a migration missing, this is because the ``settings.LANGUAGES``  has changed.

So for these third party addons its tricky because they're run under different projects with different settings.

If possible, please generate the migrations and compare them to the previous ones, it's the only way to know if a substantial change has happened.

**Comment by trawick** [comment]
I follow your hint about possible nightmare scenarios with settings (https://code.djangoproject.com/ticket/23586 and https://code.djangoproject.com/ticket/22837); I'm concerned about that for my real project, but there are still other Python 2 vs. 3 issues with the project out of the box without settings changes in the project or locally.

I'm testing with an example that shouldn't be impacted by anything like that, where I pick up a level of aldryn-newsblog and

* Django 1.7.10 + Python 2.7 thinks that migrations are fine
* Django 1.7.10 + Python 3.4 thinks that a migration is missing

But at the moment (06d96d5c3951f7ae35b5aa1d3174bb016753a371) we **also** have an ordinary missing-migration bug that appeared since I opened this issue.

Here's what Django wants to change with Python 3.4:

####  ``NewsBlogConfig.app_data`` (inherited from ``AppHookConfig``):
```
        migrations.AlterField(
            model_name='newsblogconfig',
            name='app_data',
            field=app_data.fields.AppDataField(editable=False, default='{}'),
            preserve_default=True,
        ),
```
  ``app_data`` currently looks like ``app_data = AppDataField()``.  I think the issue is that Django+Python 2 generated a migration which defines the field with ``default=b'{}'``, in https://github.com/aldryn/aldryn-newsblog/blob/master/aldryn_newsblog/migrations/0008_auto_20160106_1735.py

#### ``NewsBlogConfig.template_prefix`` (just a boring missing-migration bug)
```
        migrations.AlterField(
            model_name='newsblogconfig',
            name='template_prefix',
            field=models.CharField(blank=True, null=True, verbose_name='Prefix for template dirs', max_length=20),
            preserve_default=True,
        ),
```

The field currently looks like:

```
    template_prefix = models.CharField(
        max_length=20,
        null=True, blank=True,
        choices=TEMPLATE_PREFIX_CHOICES,
        verbose_name=_("Prefix for template dirs"))
```

The migration generated by Django 1.7.10 + Python 2.7 is exactly the same except the ``models.CharField`` parameters are rendered in a different order in the call to ``AlterField``:

```
        migrations.AlterField(
            model_name='newsblogconfig',
            name='template_prefix',
            field=models.CharField(max_length=20, null=True, verbose_name='Prefix for template dirs', blank=True),
            preserve_default=True,
        ),
```

Beyond the Python 3 issue:

What to do in a consumer?  Override the ``migrations`` directory provided by the Django CMS plugin when this happens and provide our own migrations, and carefully test when upgrading to a new plugin release?
