### ISSUE TITLE
Translations for templates: the right way.

### ISSUE THREAD

**Issue by wowkalucky** [divio/aldryn-newsblog#345]
Hi! I'm trying to get acquainted with the aldryn-apps ecosystem.

I noticed that newsblog is distributed without translations. So can you tell me is there some special "right" approach to do translations?
Or I just can help Django translation system to discover templates by overriding original templates / symlinking aldryn-newsblog templates directory to project? Thanks.

**Comment by vThaian** [comment]
Yes, we are using Transifex service.
https://www.transifex.com/divio/aldryn-newsblog/dashboard/
