### ISSUE TITLE
Article list template is not used

### ISSUE THREAD

**Issue by Collederas** [divio/aldryn-newsblog#363]
I have just installed aldryn news & blog on top of a plain new djangoCMS installation. I created a Config and added the AppHook to my Blog page. Then I created an Article.

When I navigate to the article I see that the template that is being used is my base template and not the article_list.html from aldryn app.

Can't figure out what is wrong!
Can some good soul help me? Thanks! :)

**Comment by vThaian** [comment]
I believe that you resolved your issue so I'm closing. Feel free to ping me if you have that issue still.
