### ISSUE TITLE
I can't translate articles (tabs aren't displayed) 

### ISSUE THREAD

**Issue by Nekmo** [divio/aldryn-newsblog#371]
The article is created in the default language of Parler (Spanish) but I can't edit it in other languages.

![instantanea7](https://cloud.githubusercontent.com/assets/740106/13860802/7146a5d0-ec8a-11e5-84fb-351ce6dd4843.png)

The same translating from Admin.
![instantanea7](https://cloud.githubusercontent.com/assets/740106/13860846/a94ebfbc-ec8a-11e5-8f53-92f0677c552c.png)

Parler conf:

```
PARLER_DEFAULT_LANGUAGE_CODE = 'es'

PARLER_LANGUAGES = {
    None: (
        {'code': 'en',},
        {'code': 'es',},
    ),
    'default': {
        'fallbacks': ['en', 'es'],          # defaults to PARLER_DEFAULT_LANGUAGE_CODE
        'hide_untranslated': False,   # the default; let .active_translations() return fallbacks too.
    }
}
```

**Comment by facconi** [comment]
I have the same issue.

**Comment by facconi** [comment]
I have a completely translated Django CMS website. I have added aldryn-newsblog, and a few news. When I try to translate them, they are always saved as untranslated.

**Comment by FabrizioA** [comment]
I have the same issue, How can I translate an article in another language??
The aldryn-newsblog docs doesn't explain anything about parler or multilanguage configuration....

**Comment by crsepulveda** [comment]
You need change "None" for the SITE_ID value and works
