### ISSUE TITLE
Portuguese (Brazil) translations

### ISSUE THREAD

**Issue by diegoponciano** [divio/aldryn-newsblog#416]
I would like to contribute with translations for my native language, but I don't know how to proceed.  
Should I send a PR with the .po translated, or translate only on transifex?  
In any case, I requested on transifex for `pt_BR` to be added to the list of languages.

**Comment by vThaian** [comment]
Is old but I will add answer :) Sure would be great. You can translate string using https://www.transifex.com/divio/aldryn-newsblog/ service. Cheers :)
