### ISSUE TITLE
Cannot add my url. 

### ISSUE THREAD

**Issue by maartinez** [divio/aldryn-newsblog#443]
Hi, I added a plugin with a template to my aldryn-newsblog fork. And in that template I have a button to call ajax function:

```
function getMore(){
        $.ajax({
            url: "/get_more/",
            data: {
                csrfmiddlewaretoken: '{{csrf_token}}',
            },
            type: "POST",
                success: function (content) {
                },
                error: function (_) {
                }
        });
    }
```

I also added this url to urls.py like I always did:
```
urlpatterns = [
#------------
    url(r'^get_more', views.get_more),    <----
#------------
    url(r'^$',
        ArticleList.as_view(), name='article-list'),
   ... ]
```

There is also function in views which is not called beacause I get 404 error in browser. 

![image](https://cloud.githubusercontent.com/assets/23735559/22783114/b28e1b8e-eeca-11e6-9e68-88c5a76b3d72.png)

How can I call my function there? Any help would be appreciated. Thank you.

**Comment by vThaian** [comment]
I see your url on image `dzial-nauka/get_more/` is not working? Your url in ajax doesn't contain the full path to your view.
