### ISSUE TITLE
Plugins of article always the same as parent page

### ISSUE THREAD

**Issue by LRH539** [divio/aldryn-newsblog#472]
I'm currently trying to get this blog plugin to work with Django 1.10, using the master branch of this repo. My pages have the following layout:

* Home
  * Blog
    * Article

When I create an test article and afterwards add a plugin to the Blog page which shows the most recent articles, I can see the preview of the article I've just created. If I now click on the article, I get redirected to the correct page, but the article is not empty, instead all plugins from the "Blog" page are shown.

If I now remove the plugins from the article and add a test plugin, the same will happen to the parent page. I am not sure what exactly is causing this problem. I think that I am not really looking at the article as expected, but looking at the parent page (Blog), just with a different domain.

I checked my urls.py, but I've never added any aldryn specific urls, so I'm not sure what's going wrong here.

**Comment by artforlife** [comment]
I second that this issue exist and am subscribing to the thread.

**Comment by LRH539** [comment]
As discussed in #440, I'm facing this problem with all users, because I can't even edit the article detail view, I'm always seeing the list view, so I could never publish a version which would differ for anonymous users.

**Comment by artforlife** [comment]
I am seeing the problem only for anonymous users. For administrator, it works properly, as far as I can tell.

**Comment by LRH539** [comment]
This is probably caused, because the article_list.html and article_detail.html templates are never used. I wonder how to configure the templates correctly?

**Comment by LRH539** [comment]
I found the problem. My base template did not contain a block `content` and therefore the templates have never been loaded correctly.

I suggest that the docs should definitely mention something about this.

I am not sure whether this issue is related to the behavior @artforlife is experiencing.

**Comment by artforlife** [comment]
@LRH539 What did you do exactly? Did you add `{% block content %}` to the template? Which template?

**Comment by LRH539** [comment]
@artforlife In my project directory, I have a template subdirectory, which contains all templates I am using with DjangoCMS. I am using a base.html template, which I use for all other templates such as blog.html.

Aldryn-Newsblog also uses a base.html and a article_list.html and a article_detail.html, which both extend their base.html. Their base.html (aldryn_newsblog/base.html) contained a {% block content %}, while my base.html contained a {% block main_content %}. Because I wanted to keep everything as is, to keep the design of the website consistent, I went into my blog.html, which extends my base.html and replaced a placeholder which I used to add my plugins with a {% block content %}{% endblock %} statement.

After I've done that, aldryn_newsblog extended my templates automagically and finally the Newsblog_Article_Content and Newsblog_Article_Social placeholders showed up. Now if I add my content to these Areas, everything works as intended for both my list view and my detail views.

If it remains unclear what I've done, I can send some code snippets.

**Comment by artforlife** [comment]
@LRH539 Which file does your `blog.html` correspond to? I have the following structure, which pretty much follows the original tutorial (or at least a version thereof from sometime within the last 6-7 months).
<img width="338" alt="screen shot 2017-09-19 at 4 17 38 pm" src="https://user-images.githubusercontent.com/8064423/30613462-35910e12-9d56-11e7-8d6c-7d31d8cc6389.png">

**Comment by LRH539** [comment]
@artforlife I have the following layout for my templates:

![shot1](https://user-images.githubusercontent.com/28930612/30614260-166fa73e-9d8b-11e7-85ad-c8fbf7bca63e.png)

The sub folder contains my base.html and I have not customized the aldryn_newsblog templates yet, so they are not in my project folder.

My blog.html contains the following code:

```
{% extends "sub/base.html" %}

{% block main_content %}
...
</header>
{% block content %}{% endblock %}
<footer>
...
{% endblock %}
```

The `main_content` block is present in `sub/base.html` while the other `content` block is present in the `aldryn_newsblog/base.html` (in case you haven't modified them yet).

I wasn't aware there's an official tutorial, I've only used the installation guide so far.

**Comment by artforlife** [comment]
@LRH539 I was referring to [this](http://support.divio.com/academy/basic-how-to-build-a-website-and-blog-with-django-cms-60-minutes/3-adding-a-few-pages) tutorial. Is that what you have in mind?

If that is what you are using, it would be really helpful (to me and probably others who encounter the same problem) if we can specify where in the tutorial one needs an extra step to avoid this issue. 

I have considered rebuilding using Django 1.10 from scratch, but have not committed to it yet.

**Comment by LRH539** [comment]
I've used this website, the official docs instead of a tutorial. The tutorial does indeed mention something about `{% block content %}{% endblock %}`, but the docs don't and I the info should be added.

The official docs can be found here: http://aldryn-newsblog.readthedocs.io/en/latest/introduction.html

**Comment by artforlife** [comment]
@LRH539 I see. By the way, did you grab every module from their respective repositories or you only did it with Django?

**Comment by LRH539** [comment]
I installed most applications with pip install MODULENAME, only aldryn-newsblog required me to use the latest version from github, because I didn't want to downgrade my stack to Django 1.9.

**Comment by artforlife** [comment]
After tinkering with this for awhile I did the following:

1. Installed latest Django 1.10 from its repository (branch called `stable/1.10.x`)
2. Installed latest Django CMS from its repository 
3. Installed Aldryn NewsBlog from its repository
4. I had to comment out the Aldryn Events becase it was getting the error similar to the one mentioned in [here](https://stackoverflow.com/questions/46305786/content-cannot-be-specified-for-article-model-form-as-it-is-a-non-editable-fie).
That is, I suspect that the error shows up because Aldryn Events has not been made compatible with Django 1.10.

After the above steps, the problem fixed itself! That is, in my case the problem didnt appear to be related to improper code in templates. Instead, it was related to the behavior of the modules themselves.

**Comment by tehfink** [comment]
Having the same problem in:
- Django: 1.11.22
- django-cms: 3.6.0
- aldryn-newsblog: 2.2.1 (tried with release & master)

It seems the admin's Section settings for "PERMALINK TYPE" & "NON-PERMALINK HANDLING" are ignored, and everything after the apphooked url is swallowed – thus even non-existent urls return the list view (and the template variable "detail_view" is never set, as LRH539 mentioned above).
