### ISSUE TITLE
Adding NewsBlog apphook to page breaks login: 405 error

### ISSUE THREAD

**Issue by austin-carnahan** [divio/aldryn-newsblog#501]
### Environment
Python 3.3.6
django 1.11.16
django-cms 3.5.2
aldryn-newsblog 2.1.1

### Reproducing the error

Followed installation instructions for django cms found here:
http://docs.django-cms.org/en/latest/introduction/install.html

Followed installation instructions for aldryn-newsblog found here:
https://aldryn-newsblog.readthedocs.io/en/latest/introduction.html

After adding the NewsBlog apphook to a page via *Advanced settings... > Application settings*, if I log out of the cms editor and attempt to log back in I get the 405 error below:
```
Method Not Allowed (POST): /en/cms_login/
[18/Oct/2018 20:15:05] "POST /en/cms_login/?next=/en/&edit HTTP/1.1" 405 0
```

Error does not occur before adding NewsBlog apphook to the page.

Any help here would be much appreciated. I can't seem to find documentation of this issue anywhere.
Thanks!

**Comment by b264** [comment]
I'm having this same issue

**Comment by vThaian** [comment]
@austin-carnahan please check with the newsblog `2.2.1`. We added handling post for newsblog views.
