### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by b264** [divio/aldryn-newsblog#502]
It looks like it went off the radar a few months ago.  Should folks be using [Mezzanine](https://github.com/stephenmcd/mezzanine) instead?

**Comment by b264** [comment]
Actually [wagtail](https://github.com/wagtail/wagtail) is pretty good

**Comment by b264** [comment]
It doesn't seem to work and there wasn't any activity recently and a lot of issues had no responses.  We had to switch to wagtail

**Comment by b264** [comment]
20 days for any response, and not even by a maintainer, is "off the radar" in my opinion :man_shrugging:

**Comment by marksweb** [comment]
Fair enough. It works though, but you're correct in a sense that there doesn't seem to by active development of this app.

**Comment by b264** [comment]
LoL but it doesn't work on python 2.x

Since I had to upgrade everything anyway, I just switched to Wagtail and suggest it, it seems much better and very maintained.
