### ISSUE TITLE
FieldError: Invalid field name(s) for model Person: 'name'.

### ISSUE THREAD

**Issue by adrien-delhorme** [divio/aldryn-newsblog#520]
When I create an article, without choosing an author, the save method tries to `get_or_create` it. A default dictionary that defines a `name` is passed to `get_or_create`, but due to django-parler, `name` is not an attribute of the Person model (it is in `translations__name`).
So I get the error `FieldError: Invalid field name(s) for model Person: 'name'.`

**Comment by vThaian** [comment]
On a fresh project with newsblog addon I'm able to create an article without an author. @adrien-delhorme could you please add more information such as a version of newsblog, django-cms, and django?
