### ISSUE TITLE
'CMSToolbar' object has no attribute 'edit_mode'

### ISSUE THREAD

**Issue by bruino** [divio/aldryn-newsblog#522]
This error occurs when I search for articles.
This is because the "edit_mode" attribute in CMS Toolbar is deprected in Django-CMS 3.6.

### Solution
In aldryn_newsblog / views.py, in the ArticleSearchResultsList class change:
```python
def get (self, request, * args, ** kwargs):
         self.query = request.GET.get ('q')
         self.max_articles = request.GET.get ('max_articles', 0)
         self.edit_mode = (request.toolbar and request.toolbar.edit_mode) # Change
         return super (ArticleSearchResultsList, self) .get (request, * args, ** kwargs)
```

...by:

```python
def get (self, request, * args, ** kwargs):
         self.query = request.GET.get ('q')
         self.max_articles = request.GET.get ('max_articles', 0)
         self.edit_mode = (request.toolbar and toolbar_edit_mode_active (request)) # Correct!
         return super (ArticleSearchResultsList, self) .get (request, * args, ** kwargs)
```

SORRY MY ENGLISH.

**Comment by vThaian** [comment]
@bruino thanks for added issue and solution. I checked and is resolving that issue. I will create PR based on this issue.

**Comment by michellemark** [comment]
I have this exact issue using aldryn-newsblog 2.2.1, with Django 2.1.8 and django-cms 3.6.0

**Comment by tehfink** [comment]
@vThaian: Same issue with aldryn-newsblog 2.2.1, Django 1.11.20, and django-cms 3.6.0.

**Comment by michellemark** [comment]
is there a solution coming for this issue?

**Comment by PiebaldPiper** [comment]
@bruino thank you for issue
